server:
  port: 0

spring:
  application:
    name: projects-service
  data:
    mongodb:
      database: tramways_projects
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/tramways_users?useLegacyDatetimeCode=false&serverTimezone=Europe/Rome
#    username: tramways
#    password: tramways

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
