openapi: 3.0.3
info:
  title: Tramways Roadmaps API
  description: Tramways Roadmaps API
  version: 1.0.0
servers:
  - url: http://localhost:8762/tramways/rest/
paths:
  /projects:
    post:
      operationId: 'createProject'
      summary: 'Creates a new project'
      tags: [ 'projects' ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '200':
          description: Ok
    get:
      operationId: 'getProjects'
      summary: 'Gets user projects'
      tags: [ 'projects' ]
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDescription'
  /projects/{id}:
    get:
      summary: 'Gets project'
      operationId: 'getProject'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
    put:
      summary: 'Updates a project'
      operationId: 'updateProject'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProjectRequest'
      responses:
        '200':
          description: Ok
    delete:
      summary: 'Deletes a project'
      operationId: 'deleteProject'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Ok'
  /projects/{projectId}/maps:
    post:
      summary: 'Creates a map'
      operationId: 'createMap'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMapRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadMap'
  /projects/{projectId}/maps/{mapId}:
    get:
      summary: 'Gets a map'
      operationId: 'getMap'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoadMap'
    put:
      summary: 'Updates a map'
      operationId: 'updateMap'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMapRequest'
      responses:
        '200':
          description: Ok
    delete:
      summary: 'Deletes a map'
      operationId: 'deleteMap'
      tags: [ 'projects' ]
      parameters:
        - in: path
          name: projectId
          required: true
          schema:
            type: string
        - in: path
          name: mapId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ok
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateProjectRequest:
      type: object
      properties:
        name:
          type: string
    UpdateProjectRequest:
      type: object
      properties:
        name:
          type: string
    CreateMapRequest:
      type: object
      properties:
        map:
          $ref: '#/components/schemas/RoadMap'
    UpdateMapRequest:
      type: object
      properties:
        map:
          $ref: '#/components/schemas/RoadMap'
    Project:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        owner:
          type: string
        roadMaps:
          type: array
          items:
            $ref: '#/components/schemas/RoadMapDescription'
    RoadMap:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        projectId:
          type: string
        points:
          type: array
          items:
            $ref: '#/components/schemas/RelevantPoint'
        lanes:
          type: array
          items:
            $ref: '#/components/schemas/Lane'
    RelevantPoint:
      allOf:
        - $ref: '#/components/schemas/Configurable'
        - type: object
          properties:
            links:
              type: array
              items:
                $ref: '#/components/schemas/CrossingLink'
    Lane:
      allOf:
        - $ref: '#/components/schemas/Configurable'
        - type: object
          properties:
            sourceId:
              type: string
            destinationId:
              type: string
    CrossingLink:
      allOf:
        - $ref: '#/components/schemas/Configurable'
        - type: object
          properties:
            sourceId:
              type: string
            destinationId:
              type: string
    Configurable:
      type: object
      discriminator:
        propertyName: 'configurableType'
      properties:
        id:
          type: string
        category:
          type: string
        configurableType:
          type: string
        props:
          type: array
          items:
            $ref: '#/components/schemas/Property'
    ProjectDescription:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
        owner:
          type: string
    RoadMapDescription:
      type: object
      properties:
        uuid:
          type: string
        name:
          type: string
    Property:
      type: object
      discriminator:
        propertyName: propertyType
      properties:
        name:
          type: string
        description:
          type: string
        propertyType:
          type: string
        valid:
          type: boolean
      required: [ propertyType ]
    IntegerProperty:
      allOf:
        - $ref: '#/components/schemas/Property'
        - type: object
          properties:
            value:
              type: integer
    StringProperty:
      allOf:
        - $ref: '#/components/schemas/Property'
        - type: object
          properties:
            value:
              type: string
    ChoiceProperty:
      allOf:
        - $ref: '#/components/schemas/Property'
        - type: object
          properties:
            choices:
              type: array
              items:
                $ref: '#/components/schemas/ChoiceElement'
            value:
              type: string
    ChoiceElement:
      type: object
      properties:
        id:
          type: string
        label:
          type: string
    DecimalProperty:
      allOf:
        - $ref: '#/components/schemas/Property'
        - type: object
          properties:
            value:
              type: number
    DistributionProperty:
      allOf:
        - $ref: '#/components/schemas/Property'
        - type: object
          properties:
            value:
              $ref: '#/components/schemas/Distribution'
    Distribution:
      type: object
      discriminator:
        propertyName: distributionType
        mapping:
          UNIFORM: '#/components/schemas/UniformDistribution'
          EXPONENTIAL: '#/components/schemas/ExponentialDistribution'
      properties:
        distributionType:
          $ref: '#/components/schemas/DistributionType'
      required: [ distributionType ]
    DistributionType:
      type: string
      enum: [ UNIFORM, EXPONENTIAL ]
    UniformDistribution:
      allOf:
        - $ref: '#/components/schemas/Distribution'
        - type: object
          properties:
            left:
              type: number
            right:
              type: number
    ExponentialDistribution:
      allOf:
        - $ref: '#/components/schemas/Distribution'
        - type: object
          properties:
            lambda:
              type: number
security:
  - bearerAuth: [ ]
